indent = 4
margin = 92
verbose = true
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_use_return = true
whitespace_in_kwargs = true
normalize_line_endings = "unix"
trailing_comma = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = false

